# Working with JSON
JSON (JavaScript Object Notation) is a lightweight, text-based data format used to store and exchange structured data — it's the most common format for sending data between servers, APIs, and applications on the web.

In [1]:
import pandas as pd

In [2]:
df = pd.read_json("train.json")

In [3]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# Working with SQL

**SQL (Structured Query Language)** is the standard language used to communicate with relational databases — used to create, read, update, and delete data stored in structured tables (rows and columns).

**Core idea**

Data in SQL databases is organized into tables (like spreadsheets), where each table has columns (fields) and rows (records). SQL is how you query, filter, join, and manipulate this data.

In [8]:
# Need library
!pip install mysql.connector
import mysql.connector

Requirement already satisfied: mysql.connector in c:\users\bilal\anaconda3\lib\site-packages (2.2.9)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\bilal\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\bilal\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\bilal\anaconda3\Lib\site-packages)

In [22]:
# Create connection between data base

con = mysql.connector.connect(host="localhost",user='root',password='',database='world')
con

In [17]:
pd.read_sql_query("SELECT * FROM city", con)

C:\Users\bilal\AppData\Local\Temp\ipykernel_8592\4158175699.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city", con)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [20]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'PAK'", con)

C:\Users\bilal\AppData\Local\Temp\ipykernel_8592\3390971073.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'PAK'", con)

      ID              Name CountryCode              District  Population
0   2822           Karachi         PAK                 Sindh     9269265
1   2823            Lahore         PAK                Punjab     5063499
2   2824        Faisalabad         PAK                Punjab     1977246
3   2825        Rawalpindi         PAK                Punjab     1406214
4   2826            Multan         PAK                Punjab     1182441
5   2827         Hyderabad         PAK                 Sindh     1151274
6   2828        Gujranwala         PAK                Punjab     1124749
7   2829          Peshawar         PAK  Nothwest Border Prov      988005
8   2830            Quetta         PAK           Baluchistan      560307
9   2831         Islamabad         PAK             Islamabad      524500
10  2832          Sargodha         PAK                Punjab      455360
11  2833           Sialkot         PAK                Punjab      417597
12  2834        Bahawalpur         PAK                Punjab      403408
13  2835            Sukkur         PAK                 Sindh      329176
14  2836             Jhang         PAK                Punjab      292214
15  2837       Sheikhupura         PAK                Punjab      271875
16  2838           Larkana         PAK                 Sindh      270366
17  2839            Gujrat         PAK                Punjab      250121
18  2840            Mardan         PAK  Nothwest Border Prov      244511
19  2841             Kasur         PAK                Punjab      241649
20  2842    Rahim Yar Khan         PAK                Punjab      228479
21  2843           Sahiwal         PAK                Punjab      207388
22  2844             Okara         PAK                Punjab      200901
23  2845               Wah         PAK                Punjab      198400
24  2846   Dera Ghazi Khan         PAK                Punjab      188100
25  2847       Mirpur Khas         PAK                  Sind      184500
26  2848         Nawabshah         PAK                  Sind      183100
27  2849           Mingora         PAK  Nothwest Border Prov      174500
28  2850           Chiniot         PAK                Punjab      169300
29  2851            Kamoke         PAK                Punjab      151000
30  2852    Mandi Burewala         PAK                Punjab      149900
31  2853            Jhelum         PAK                Punjab      145800
32  2854         Sadiqabad         PAK                Punjab      141500
33  2855         Jacobabad         PAK                  Sind      137700
34  2856         Shikarpur         PAK                  Sind      133300
35  2857          Khanewal         PAK                Punjab      133000
36  2858         Hafizabad         PAK                Punjab      130200
37  2859             Kohat         PAK  Nothwest Border Prov      125300
38  2860      Muzaffargarh         PAK                Punjab      121600
39  2861           Khanpur         PAK                Punjab      117800
40  2862             Gojra         PAK                Punjab      115000
41  2863      Bahawalnagar         PAK                Punjab      109600
42  2864           Muridke         PAK                Punjab      108600
43  2865        Pak Pattan         PAK                Punjab      107800
44  2866         Abottabad         PAK  Nothwest Border Prov      106000
45  2867        Tando Adam         PAK                  Sind      103400
46  2868         Jaranwala         PAK                Punjab      103300
47  2869          Khairpur         PAK                  Sind      102200
48  2870   Chishtian Mandi         PAK                Punjab      101700
49  2871             Daska         PAK                Punjab      101500
50  2872              Dadu         PAK                  Sind       98600
51  2873   Mandi Bahauddin         PAK                Punjab       97300
52  2874     Ahmadpur East         PAK                Punjab       96000
53  2875           Kamalia         PAK                Punjab       95300
54  2876           Khuzdar         PAK           Baluchistan       93100
55  2877            Vihari         PAK                Punjab       92300
56  2878  Dera Ismail Khan         PAK  Nothwest Border Prov       90400
57  2879         Wazirabad         PAK                Punjab       89700
58  2880          Nowshera         PAK  Nothwest Border Prov       89400

In [ ]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'", con)