## Pipelines

- chain togather multiple steps so that output of each step is used as input of next step.
- pipeline make it easy to apply the same preprocessing to train and test.

In [11]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [12]:
df = pd.read_csv('train.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.drop(columns = ['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace = True)

In [14]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

## STEP 1: Train test split

In [15]:

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns = ['Survived']),
                                                   df['Survived'],
                                                    test_size = 0.2,
                                                    random_state=42
                                                   )

In [16]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [17]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

## STEP 2: CHECK MISSING VALUES

In [18]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

### Filling Missing values by applying Immutation

In [19]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy = 'most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [26]:
# x_train_age

In [29]:
# x_train_embarked

In [22]:
x_train_embarked = x_train_embarked.toarray()
x_test_embarked = x_test_embarked.toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [ ]:
# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)

In [ ]:
print(type(x_train_age))
print(type(x_train_embarked))

In [ ]:
x_train_sex

In [ ]:
x_train_embarked

In [23]:
df = pd.read_csv("asiacup.csv")

In [31]:
df.sample(5)

,Team,Opponent,Format,Ground,Year,Toss,Selection,Run Scored,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Player Of The Match,Result
103,India,Sri Lanka,ODI,Colombo(RPS),2004,Lose,Bowling,203.0,9.0,13.0,3.0,25.0,4.06,58.39,74.0,9.0,32.0,2.0,Marvan Atapattu,Lose
63,India,Sri Lanka,ODI,Colombo(RPS),1997,Win,Batting,239.0,7.0,11.0,2.0,15.0,4.78,91.52,81.0,2.0,25.0,1.0,Marvan Atapattu,Lose
81,UAE,India,ODI,Dambulla,2004,Lose,Bowling,144.0,10.0,14.0,0.0,34.0,4.11,34.93,55.0,6.0,14.0,2.0,Rahul Dravid,Lose
126,Pakistan,Bangladesh,ODI,Karachi,2008,Lose,Bowling,116.0,0.0,14.0,2.0,8.0,5.89,91.59,56.0,10.0,16.0,3.0,Abdur Rauf,Win
55,India,Sri Lanka,ODI,Colombo(RPS),1997,Lose,Batting,227.0,6.0,19.0,2.0,4.0,4.54,86.79,81.0,4.0,21.0,2.0,Arjuna Ranatunga,Lose

In [32]:
df.drop(columns = ['Ground', 'Year', 'Player Of The Match'], inplace = True)

In [34]:
df.sample(5)

,Team,Opponent,Format,Toss,Selection,Run Scored,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Result
61,India,Bangladesh,ODI,Win,Bowling,132.0,1.0,16.0,2.0,8.0,8.80,129.57,73.0,8.0,19.0,3.0,Win
113,India,Pakistan,ODI,Lose,Bowling,301.0,4.0,25.0,12.0,15.0,7.13,85.13,119.0,4.0,7.0,1.0,Win
132,Bangladesh,India,ODI,Win,Batting,167.0,10.0,15.0,1.0,21.0,4.79,61.70,37.0,4.0,25.0,2.0,Lose
20,Bangladesh,Pakistan,ODI,Lose,Bowling,111.0,6.0,0.0,0.0,15.0,2.46,31.02,22.0,3.0,23.0,1.0,Lose
153,Pakistan,India,ODI,Win,Batting,329.0,6.0,27.0,2.0,15.0,6.58,86.28,112.0,4.0,11.0,2.0,Lose

In [35]:
df.isnull().sum()

Team                         0
Opponent                     0
Format                       0
Toss                         0
Selection                    0
Run Scored                   2
Wicket Lost                  2
Fours                        2
Sixes                        2
Extras                       2
Run Rate                     2
Avg Bat Strike Rate          2
Highest Score                2
Wicket Taken                 2
Given Extras                 2
Highest Individual wicket    2
Result                       0
dtype: int64

In [36]:
df.shape

(254, 17)

In [40]:
df[df['Run Scored'].isnull()]

,Team,Opponent,Format,Toss,Selection,Run Scored,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Result
56,India,Pakistan,ODI,Win,Bowling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Result
57,Pakistan,India,ODI,Lose,Batting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Result

In [60]:
df.dropna(inplace = True)

In [61]:
df.shape

(252, 17)

In [62]:
df.sample(5)

,Team,Opponent,Format,Toss,Selection,Run Scored,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Result
35,Sri Lanka,India,ODI,Lose,Batting,204.0,9.0,3.0,0.0,21.0,4.53,55.73,49.0,3.0,2.0,1.0,Lose
218,India,Pakistan,ODI,Lose,Bowling,238.0,1.0,24.0,6.0,1.0,6.02,91.31,114.0,7.0,8.0,2.0,Win
49,Sri Lanka,India,ODI,Lose,Batting,230.0,7.0,12.0,3.0,37.0,4.60,72.28,85.0,2.0,9.0,1.0,Lose
126,Pakistan,Bangladesh,ODI,Lose,Bowling,116.0,0.0,14.0,2.0,8.0,5.89,91.59,56.0,10.0,16.0,3.0,Win
87,Pakistan,Hong Kong,ODI,Win,Batting,343.0,5.0,24.0,6.0,13.0,6.86,136.56,144.0,10.0,29.0,4.0,Win

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 252 entries, 0 to 253
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Team                       252 non-null    object
 1   Opponent                   252 non-null    object
 2   Format                     252 non-null    object
 3   Toss                       252 non-null    object
 4   Selection                  252 non-null    object
 5   Run Scored                 252 non-null    float64
 6   Wicket Lost                252 non-null    float64
 7   Fours                      252 non-null    float64
 8   Sixes                      252 non-null    float64
 9   Extras                     252 non-null    float64
 10  Run Rate                   252 non-null    float64
 11  Avg Bat Strike Rate        252 non-null    float64
 12  Highest Score              252 non-null    float64
 13  Wicket Taken               252 non-null    float64
 14  Given Extras               252 non-null    float64
 15  Highest Individual wicket  252 non-null    float64
 16  Result                     252 non-null    object
dtypes: float64(11), object(6)
memory usage: 35.4+ KB

In [64]:
df.describe()

,Run Scored,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket
count,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000
mean,201.920635,6.892857,15.626984,2.912698,13.238095,5.308214,76.676667,69.309524,6.892857,13.238095,2.563492
std,67.331860,2.874609,7.754946,2.596411,7.621973,1.584823,30.678228,29.813488,2.874609,7.621973,1.100496
min,38.000000,0.000000,0.000000,0.000000,0.000000,2.200000,24.630000,8.000000,0.000000,0.000000,0.000000
25%,147.000000,5.000000,10.000000,1.000000,8.000000,4.227500,54.742500,47.000000,5.000000,8.000000,2.000000
50%,193.000000,7.000000,15.000000,2.000000,12.000000,5.090000,73.155000,66.500000,7.000000,12.000000,3.000000
75%,253.250000,10.000000,20.000000,4.250000,18.000000,6.100000,92.897500,85.000000,10.000000,18.000000,3.000000
max,385.000000,10.000000,41.000000,14.000000,38.000000,10.600000,194.050000,183.000000,10.000000,38.000000,6.000000

In [65]:
df['Result'].value_counts()

Result
Lose         125
Win          125
No Result      2
Name: count, dtype: int64

In [66]:
df['Result'] = df['Result'].str.strip() # Use to remove white space of all the values in a column
df['Result'] = df['Result'].replace({
    'win' : 'Win',
    'Win D/L' : 'Win',
    'Lose D/L': 'Lose'
})

In [67]:

df['Result'].value_counts()

Result
Lose         125
Win          125
No Result      2
Name: count, dtype: int64

In [69]:
df.dropna(inplace = True)

In [71]:
df['Result'].value_counts()

Result
Lose         125
Win          125
No Result      2
Name: count, dtype: int64

In [74]:
df = df[df['Result'] != 'No Result']

In [ ]:
df['Result']